In [ ]:
import scipy.sparse as sp
import numpy as np

In [ ]:
# Tm 
Tm = sp.diags([-1, 4, -1], [-1, 0, 1], shape=(3,3), format='csr')

# negative identity block
I = sp.diags([-1], [0], shape=(3,3), format='csr')
# zero block
zero = sp.csr_matrix((3,3))

A_sparse = sp.bmat([
    [Tm, I, zero],
    [I, Tm, I],
    [zero, I, Tm]
], format='csr')

# convert to dense array
A = A_sparse.toarray()

print(A)

[[ 4. -1.  0. -1.  0.  0.  0.  0.  0.]
 [-1.  4. -1.  0. -1.  0.  0.  0.  0.]
 [ 0. -1.  4.  0.  0. -1.  0.  0.  0.]
 [-1.  0.  0.  4. -1.  0. -1.  0.  0.]
 [ 0. -1.  0. -1.  4. -1.  0. -1.  0.]
 [ 0.  0. -1.  0. -1.  4.  0.  0. -1.]
 [ 0.  0.  0. -1.  0.  0.  4. -1.  0.]
 [ 0.  0.  0.  0. -1.  0. -1.  4. -1.]
 [ 0.  0.  0.  0.  0. -1.  0. -1.  4.]]


In [21]:
np.linalg.det(A)

np.float64(100352.00000000013)

In [ ]:
np.linalg.inv(A)
# divide by h^2

array([[0.29910714, 0.09821429, 0.03125   , 0.09821429, 0.0625    ,
        0.02678571, 0.03125   , 0.02678571, 0.01339286],
       [0.09821429, 0.33035714, 0.09821429, 0.0625    , 0.125     ,
        0.0625    , 0.02678571, 0.04464286, 0.02678571],
       [0.03125   , 0.09821429, 0.29910714, 0.02678571, 0.0625    ,
        0.09821429, 0.01339286, 0.02678571, 0.03125   ],
       [0.09821429, 0.0625    , 0.02678571, 0.33035714, 0.125     ,
        0.04464286, 0.09821429, 0.0625    , 0.02678571],
       [0.0625    , 0.125     , 0.0625    , 0.125     , 0.375     ,
        0.125     , 0.0625    , 0.125     , 0.0625    ],
       [0.02678571, 0.0625    , 0.09821429, 0.04464286, 0.125     ,
        0.33035714, 0.02678571, 0.0625    , 0.09821429],
       [0.03125   , 0.02678571, 0.01339286, 0.09821429, 0.0625    ,
        0.02678571, 0.29910714, 0.09821429, 0.03125   ],
       [0.02678571, 0.04464286, 0.02678571, 0.0625    , 0.125     ,
        0.0625    , 0.09821429, 0.33035714, 0.09821429],
